/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CAsyncRouterView: typeof import('./ui/c-async-router-view/CAsyncRouterView.vue')['default']
    CategoriesBilateral: typeof import('./components/categories/Bilateral.vue')['default']
    CategoriesDefault: typeof import('./components/categories/Default.vue')['default']
    CategoriesDefaultPage: typeof import('./components/categories/DefaultPage.vue')['default']
    CEmpty: typeof import('./ui/c-empty/CEmpty.vue')['default']
    DictDef: typeof import('./components/dict/Def.vue')['default']
    DictDefinition: typeof import('./components/dict/Definition.vue')['default']
    DictDefinitionList: typeof import('./components/dict/DefinitionList.vue')['default']
    DictDefinitions: typeof import('./components/dict/Definitions.vue')['default']
    DictDefinitionsContainer: typeof import('./components/dict/DefinitionsContainer.vue')['default']
    DictLabel: typeof import('./components/dict/Label.vue')['default']
    DictPhraseDef: typeof import('./components/dict/PhraseDef.vue')['default']
    DictRubyText: typeof import('./components/dict/RubyText.vue')['default']
    DictSearchableText: typeof import('./components/dict/SearchableText.vue')['default']
    DictSearchableTextParser: typeof import('./components/dict/SearchableTextParser.vue')['default']
    DictTextParser: typeof import('./components/dict/TextParser.vue')['default']
    DictTranslation: typeof import('./components/dict/Translation.vue')['default']
    FormProvider: typeof import('./components/FormProvider.vue')['default']
    HeaderBase: typeof import('./components/header/Base.vue')['default']
    HeaderPage: typeof import('./components/header/Page.vue')['default']
    HeaderSearchForm: typeof import('./components/header/SearchForm.vue')['default']
    MultiColumnList: typeof import('./components/MultiColumnList.vue')['default']
    MultiColumnVirtualList: typeof import('./components/MultiColumnVirtualList.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NSpace: typeof import('naive-ui')['NSpace']
    NVirtualList: typeof import('naive-ui')['NVirtualList']
    RadicalList: typeof import('./components/radical/List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RubyText: typeof import('./components/RubyText.vue')['default']
    TextParser: typeof import('./components/TextParser.vue')['default']
  }
}
