/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CAsyncRouterView: typeof import('./ui/c-async-router-view/CAsyncRouterView.vue')['default']
    CEmpty: typeof import('./ui/c-empty/CEmpty.vue')['default']
    DictDefinition: typeof import('./components/dict/Definition.vue')['default']
    DictDefinitionList: typeof import('./components/dict/DefinitionList.vue')['default']
    DictDefinitionsContainer: typeof import('./components/dict/DefinitionsContainer.vue')['default']
    DictLabel: typeof import('./components/dict/Label.vue')['default']
    DictPlayButton: typeof import('./components/dict/PlayButton.vue')['default']
    DictRubyText: typeof import('./components/dict/RubyText.vue')['default']
    DictSearchableText: typeof import('./components/dict/SearchableText.vue')['default']
    DictSearchableTextParser: typeof import('./components/dict/SearchableTextParser.vue')['default']
    DictTextParser: typeof import('./components/dict/TextParser.vue')['default']
    DictTextToSpeechProvider: typeof import('./components/dict/TextToSpeechProvider.vue')['default']
    DictTextToSpeechRowProvider: typeof import('./components/dict/TextToSpeechRowProvider.vue')['default']
    DictTranslation: typeof import('./components/dict/Translation.vue')['default']
    FormProvider: typeof import('./components/FormProvider.vue')['default']
    HeaderBase: typeof import('./components/header/Base.vue')['default']
    HeaderPage: typeof import('./components/header/Page.vue')['default']
    HeaderSearchForm: typeof import('./components/header/SearchForm.vue')['default']
    IconMicrophone: typeof import('./components/icon/Microphone.vue')['default']
    IconPause: typeof import('./components/icon/Pause.vue')['default']
    IconStart: typeof import('./components/icon/Start.vue')['default']
    IconStop: typeof import('./components/icon/Stop.vue')['default']
    InputRecord: typeof import('./components/InputRecord.vue')['default']
    ModalRecord: typeof import('./components/modal/Record.vue')['default']
    MultiColumnVirtualList: typeof import('./components/MultiColumnVirtualList.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NH1: typeof import('naive-ui')['NH1']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NVirtualList: typeof import('naive-ui')['NVirtualList']
    RadicalList: typeof import('./components/radical/List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
